export const themeTokens = {
  colors: {
    black: "#1a1a1a",
    white: "#f5f5f5",
    surface: "#FDFDFD",
    onSurface: "#1a1a1a",
    primary: "#f54a00",
    onPrimary: "#f5f5f5",
    secondary: "#99a1af",
    onSecondary: "#f5f5f5",
    success: "#16A34A",
    onSuccess: "#f5f5f5",
    warning: "#D97706",
    onWarning: "#f5f5f5",
    error: "#DC2626",
    onError: "#f5f5f5",
  },
  radius: {
    none: "0rem",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "1rem",
    full: "9999px",
    default: "0.5rem",
  },
  spacing: {
    none: "0rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
  },
  typography: {
    fontFamily: {
      body: "'Satoshi-Variable', sans-serif",
      heading: "'ClashDisplay-Variable', sans-serif",
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.5rem",
      "2xl": "1.875rem",
      "3xl": "2.25rem",
      "4xl": "3rem",
    },
    fontWeight: {
      thin: "100",
      extraLight: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
      extraBold: "800",
      black: "900",
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      base: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
  },
};

export type ThemeTokens = typeof themeTokens;
