export enum APP_ERROR_ENUM {
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  PROMISE_REJECTION = "PROMISE_REJECTION",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}
